### ISSUE TITLE
Normalize dimension value can return too-long values

### ISSUE THREAD

**Issue by dyladan** [dynatrace-oss/dynatrace-metric-utils-go#7]
Following test case for normalize dimension value fails

```go
		{
			name: "invalid truncate value too long with escaped chars",
			args: args{value: strings.Repeat("=", 270)},
			want: strings.Repeat(`\=`, 125),
		},
```

The line length calculation and trimming is done before special characters are escaped which grows the length of the line.

**Comment by pirgeo** [comment]
Fixed by https://github.com/dynatrace-oss/dynatrace-metric-utils-go/pull/8.
